2024-11-14 08:05:25.148 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-11-14 08:05:25.162 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-11-14 08:05:25.167 [info] Experiment 'pythonTestAdapter' is active
2024-11-14 08:05:25.177 [warning] Dir "/container/pyspark_workspace/.pixi/envs" is not watchable (directory does not exist)
2024-11-14 08:05:25.182 [info] Starting Environment refresh
2024-11-14 08:05:25.205 [info] Searching for interpreters in posix paths locator
2024-11-14 08:05:25.218 [info] Searching for pyenv environments
2024-11-14 08:05:25.221 [info] Searching for conda environments
2024-11-14 08:05:25.229 [info] Searching for global virtual environments
2024-11-14 08:05:25.233 [info] Searching for custom virtual environments
2024-11-14 08:05:25.236 [info] pyenv is not installed
2024-11-14 08:05:25.242 [info] Finished searching for pyenv environments: 2203 milliseconds
2024-11-14 08:05:25.247 [info] Finished searching for custom virtual envs: 2201 milliseconds
2024-11-14 08:05:25.252 [info] > conda info --json
2024-11-14 08:05:25.255 [info] > hatch env show --json
2024-11-14 08:05:25.258 [info] cwd: .
2024-11-14 08:05:25.265 [info] Finished searching for global virtual envs: 5874 milliseconds
2024-11-14 08:05:25.267 [info] > pyenv which python
2024-11-14 08:05:25.270 [info] cwd: .
2024-11-14 08:05:25.273 [info] Found: /bin/python3 --> /bin/python3.11
2024-11-14 08:05:26.439 [info] Found: /bin/python3.11 --> /bin/python3.11
2024-11-14 08:05:29.634 [info] Found: /usr/bin/python3 --> /usr/bin/python3.11
2024-11-14 08:05:29.661 [info] > D:\Program Files\Python\python.exe -c "import sys;print(sys.executable)"
2024-11-14 08:05:29.667 [info] Found: /usr/bin/python3.11 --> /usr/bin/python3.11
2024-11-14 08:05:29.757 [error] Error: Command failed: D:\Program Files\Python\python.exe -c "import sys;print(sys.executable)"
/bin/sh: 1: D:Program: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:531:35)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:339:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'D:\\Program Files\\Python\\python.exe -c "import sys;print(sys.executable)"'
}
2024-11-14 08:05:30.961 [info] > "D:\Program Files\Python\python.exe" -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-14 08:05:31.331 [error] Error: Command failed: "D:\Program Files\Python\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
/bin/sh: 1: D:\Program Files\Python\python.exe: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:531:35)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:339:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: '"D:\\Program Files\\Python\\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py'
}
2024-11-14 08:05:31.801 [info] Found: /usr/local/bin/python --> /usr/local/bin/python3.11
2024-11-14 08:05:32.005 [info] Found: /usr/local/bin/python3 --> /usr/local/bin/python3.11
2024-11-14 08:05:32.026 [info] Found: /usr/local/bin/python3.11 --> /usr/local/bin/python3.11
2024-11-14 08:05:32.336 [info] > /bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-14 08:05:32.456 [info] Finished searching for interpreters in posix paths locator: 14319 milliseconds
2024-11-14 08:05:32.458 [info] > /usr/bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-14 08:05:32.971 [info] Environments refresh paths discovered (event): 14855 milliseconds
2024-11-14 08:05:32.972 [info] Environments refresh paths discovered: 14857 milliseconds
2024-11-14 08:05:33.274 [info] > /usr/local/bin/python -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-14 08:05:33.702 [info] > "D:\Program Files\Python\python.exe" -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-14 08:05:33.778 [error] Error: Command failed: "D:\Program Files\Python\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
/bin/sh: 1: D:\Program Files\Python\python.exe: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:531:35)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:339:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: '"D:\\Program Files\\Python\\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py'
}
2024-11-14 08:05:34.907 [info] Environments refresh finished (event): 16792 milliseconds
2024-11-14 08:05:35.327 [info] Environment refresh took 17215 milliseconds
2024-11-14 08:05:47.599 [info] Starting Pylance language server.
