2024-11-20 15:52:24.190 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-11-20 15:52:24.191 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-11-20 15:52:24.191 [info] Experiment 'pythonTestAdapter' is active
2024-11-20 15:52:24.192 [warning] Dir "/container/pyspark_workspace/.pixi/envs" is not watchable (directory does not exist)
2024-11-20 15:52:24.192 [info] > pyenv which python
2024-11-20 15:52:24.193 [info] cwd: .
2024-11-20 15:52:24.358 [info] > conda info --json
2024-11-20 15:52:26.128 [info] > D:\Program Files\Python\python.exe -c "import sys;print(sys.executable)"
2024-11-20 15:52:26.670 [error] Error: Command failed: D:\Program Files\Python\python.exe -c "import sys;print(sys.executable)"
/bin/sh: 1: D:Program: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:531:35)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:339:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'D:\\Program Files\\Python\\python.exe -c "import sys;print(sys.executable)"'
}
2024-11-20 15:52:39.294 [info] Starting Pylance language server.
2024-11-20 15:58:32.593 [info] Starting Environment refresh
2024-11-20 15:58:32.596 [info] Searching for interpreters in posix paths locator
2024-11-20 15:58:32.607 [info] Searching for pyenv environments
2024-11-20 15:58:32.612 [info] Searching for conda environments
2024-11-20 15:58:32.653 [info] Searching for global virtual environments
2024-11-20 15:58:32.655 [info] Searching for custom virtual environments
2024-11-20 15:58:32.685 [info] > hatch env show --json
2024-11-20 15:58:32.686 [info] cwd: .
2024-11-20 15:58:32.698 [info] pyenv is not installed
2024-11-20 15:58:32.699 [info] Finished searching for pyenv environments: 100 milliseconds
2024-11-20 15:58:32.701 [info] Finished searching for custom virtual envs: 101 milliseconds
2024-11-20 15:58:32.734 [info] Finished searching for global virtual envs: 134 milliseconds
2024-11-20 15:58:32.740 [info] Found: /bin/python3 --> /bin/python3.11
2024-11-20 15:58:32.745 [info] Found: /bin/python3.11 --> /bin/python3.11
2024-11-20 15:58:32.799 [info] Found: /usr/bin/python3 --> /usr/bin/python3.11
2024-11-20 15:58:32.804 [info] Found: /usr/bin/python3.11 --> /usr/bin/python3.11
2024-11-20 15:58:32.860 [info] Found: /usr/local/bin/python --> /usr/local/bin/python3.11
2024-11-20 15:58:32.863 [info] Found: /usr/local/bin/python3 --> /usr/local/bin/python3.11
2024-11-20 15:58:32.893 [info] > "D:\Program Files\Python\python.exe" -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-20 15:58:32.895 [info] Found: /usr/local/bin/python3.11 --> /usr/local/bin/python3.11
2024-11-20 15:58:32.937 [error] Error: Command failed: "D:\Program Files\Python\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
/bin/sh: 1: D:\Program Files\Python\python.exe: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:531:35)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:339:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: '"D:\\Program Files\\Python\\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py'
}
2024-11-20 15:58:33.036 [info] > /bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-20 15:58:33.110 [info] Finished searching for interpreters in posix paths locator: 509 milliseconds
2024-11-20 15:58:33.111 [info] > /usr/bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-20 15:58:33.192 [info] Environments refresh paths discovered (event): 613 milliseconds
2024-11-20 15:58:33.193 [info] Environments refresh paths discovered: 614 milliseconds
2024-11-20 15:58:33.562 [info] > /usr/local/bin/python -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-20 15:58:35.075 [info] > "D:\Program Files\Python\python.exe" -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-20 15:58:35.082 [error] Error: Command failed: "D:\Program Files\Python\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
/bin/sh: 1: D:\Program Files\Python\python.exe: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:531:35)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:339:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: '"D:\\Program Files\\Python\\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py'
}
2024-11-20 15:58:35.106 [info] Environments refresh finished (event): 2524 milliseconds
2024-11-20 15:58:35.140 [info] Environment refresh took 2567 milliseconds
2024-11-20 16:19:22.091 [info] Discover tests for workspace name: pyspark_workspace - uri: /container/pyspark_workspace/source_code/utils.py
2024-11-20 16:19:56.477 [info] Discover tests for workspace name: pyspark_workspace - uri: /container/pyspark_workspace/source_code/utils/spark.py
2024-11-20 16:26:42.279 [info] Discover tests for workspace name: pyspark_workspace - uri: /container/pyspark_workspace/source_code/utils/spark.py
