2024-11-21 03:10:24.052 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-11-21 03:10:24.058 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-11-21 03:10:24.059 [info] Experiment 'pythonTestAdapter' is active
2024-11-21 03:10:24.059 [warning] Dir "/container/pyspark_workspace/.pixi/envs" is not watchable (directory does not exist)
2024-11-21 03:10:25.217 [info] > pyenv which python
2024-11-21 03:10:25.217 [info] cwd: .
2024-11-21 03:10:26.439 [info] > conda info --json
2024-11-21 03:10:29.277 [info] > D:\Program Files\Python\python.exe -c "import sys;print(sys.executable)"
2024-11-21 03:10:29.322 [error] Error: Command failed: D:\Program Files\Python\python.exe -c "import sys;print(sys.executable)"
/bin/sh: 1: D:Program: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:531:35)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:339:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'D:\\Program Files\\Python\\python.exe -c "import sys;print(sys.executable)"'
}
2024-11-21 03:10:44.257 [info] Starting Pylance language server.
2024-11-21 03:13:32.823 [info] Starting Environment refresh
2024-11-21 03:13:32.826 [info] Searching for interpreters in posix paths locator
2024-11-21 03:13:32.834 [info] Searching for pyenv environments
2024-11-21 03:13:32.840 [info] Searching for conda environments
2024-11-21 03:13:32.842 [info] Searching for global virtual environments
2024-11-21 03:13:32.843 [info] Searching for custom virtual environments
2024-11-21 03:13:32.897 [info] > hatch env show --json
2024-11-21 03:13:32.904 [info] cwd: .
2024-11-21 03:13:33.475 [info] pyenv is not installed
2024-11-21 03:13:33.482 [info] Finished searching for pyenv environments: 646 milliseconds
2024-11-21 03:13:33.488 [info] Finished searching for custom virtual envs: 654 milliseconds
2024-11-21 03:13:33.522 [info] Finished searching for global virtual envs: 691 milliseconds
2024-11-21 03:13:33.561 [info] Found: /bin/python3 --> /bin/python3.11
2024-11-21 03:13:33.565 [info] Found: /bin/python3.11 --> /bin/python3.11
2024-11-21 03:13:33.781 [info] > "D:\Program Files\Python\python.exe" -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-21 03:13:33.878 [info] Found: /usr/bin/python3 --> /usr/bin/python3.11
2024-11-21 03:13:33.884 [info] Found: /usr/bin/python3.11 --> /usr/bin/python3.11
2024-11-21 03:13:33.931 [error] Error: Command failed: "D:\Program Files\Python\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
/bin/sh: 1: D:\Program Files\Python\python.exe: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:531:35)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:339:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: '"D:\\Program Files\\Python\\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py'
}
2024-11-21 03:13:33.958 [info] Found: /usr/local/bin/python --> /usr/local/bin/python3.11
2024-11-21 03:13:33.965 [info] Found: /usr/local/bin/python3 --> /usr/local/bin/python3.11
2024-11-21 03:13:33.966 [info] Found: /usr/local/bin/python3.11 --> /usr/local/bin/python3.11
2024-11-21 03:13:34.091 [info] > /bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-21 03:13:34.212 [info] Finished searching for interpreters in posix paths locator: 1378 milliseconds
2024-11-21 03:13:34.213 [info] > /usr/bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-21 03:13:34.379 [info] Environments refresh paths discovered (event): 1573 milliseconds
2024-11-21 03:13:34.379 [info] Environments refresh paths discovered: 1574 milliseconds
2024-11-21 03:13:34.633 [info] > /usr/local/bin/python -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-21 03:13:36.090 [info] > "D:\Program Files\Python\python.exe" -I ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
2024-11-21 03:13:36.464 [error] Error: Command failed: "D:\Program Files\Python\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py
/bin/sh: 1: D:\Program Files\Python\python.exe: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:531:35)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:339:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: '"D:\\Program Files\\Python\\python.exe" -I /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2024.20.0-linux-x64/python_files/interpreterInfo.py'
}
2024-11-21 03:13:36.498 [info] Environments refresh finished (event): 3689 milliseconds
2024-11-21 03:13:36.560 [info] Environment refresh took 3767 milliseconds
2024-11-21 03:15:30.811 [info] Discover tests for workspace name: pyspark_workspace - uri: /container/pyspark_workspace/source_code/generate_data/generate_dummy_data.py
